/**
 * css-lint.test.mjs — validates styles/app.css with css-tree + csstree-validator.
 *
 * There is no browser in this sandbox, so a real CSS parser plus the property
 * dictionary is what stands between a typo and a broken layout. Skips itself
 * when the dev dependencies are absent.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CSS_FILE = join(ROOT, 'styles', 'app.css');
const CSS = readFileSync(CSS_FILE, 'utf8');

let csstree = null;
let validator = null;
try {
  csstree = await import('css-tree');
  validator = require('csstree-validator');
} catch {
  csstree = null;
}

test('the stylesheet parses and uses only known properties', { skip: csstree ? false : 'css-tree not installed' }, () => {
  const parseErrors = [];
  const ast = csstree.parse(CSS, { positions: true, filename: 'app.css', onParseError: (e) => parseErrors.push(e.message) });
  assert.deepEqual(parseErrors, [], 'css-tree reported parse errors');

  const custom = new Set([...csstree.findAll(ast, (n) => n.type === 'Declaration' && /^--/.test(n.property))].map((n) => n.property));
  const used = new Set();
  for (const node of csstree.findAll(ast, (n) => n.type === 'Function' && n.name === 'var')) {
    const first = node.children?.first;
    if (first?.name) used.add(first.name);
  }
  for (const name of used) assert.ok(custom.has(name), `var(${name}) is never defined`);

  const report = validator.validateString(CSS, 'app.css');
  const list = Array.isArray(report) ? report : (report?.errors ?? []);
  // Custom properties in our own dictionary confuse some validators; only
  // report genuine unknown-property/unknown-value problems.
  const real = (Array.isArray(list) ? list : []).filter((e) => !/--/.test(String(e.message)));
  assert.deepEqual(real.map((e) => `${e.line}:${e.column} ${e.message}`), [], 'csstree-validator found problems');
});

test('every element the JS creates with a class has a rule behind it', { skip: csstree ? false : 'css-tree not installed' }, async () => {
  const { readFile } = await import('node:fs/promises');
  const main = await readFile(join(ROOT, 'js', 'main.js'), 'utf8');
  const classes = new Set();
  for (const m of main.matchAll(/class: '([a-z0-9_ -]+)'/g)) m[1].split(/\s+/).forEach((c) => c && classes.add(c));
  const ast = csstree.parse(CSS, { positions: true });
  const selectors = [...csstree.findAll(ast, (n) => n.type === 'Selector')].map((s) => csstree.generate(s));
  const missing = [...classes].filter((c) => !selectors.some((s) => s.includes(`.${c}`)));
  assert.deepEqual(missing, [], `unstyled classes generated by main.js: ${missing.join(', ')}`);
  assert.ok(classes.size > 15, 'this test is meaningful only if classes were collected');
});

test('no leftover TODOs or debug hooks ship in the CSS', () => {
  assert.doesNotMatch(CSS, /\/\*\s*(TODO|FIXME|XXX)/i, 'unresolved comment marker');
  assert.doesNotMatch(CSS, /outline:\s*none\s*(!important)?\s*\n?\s*\}/, 'a focus ring must never be removed bare');
  assert.ok(CSS.includes('prefers-reduced-motion'), 'motion must be reducible');
});
