/**
 * styles.test.mjs — the stylesheet is parsed by jsdom, so this catches CSS
 * syntax errors, unbalanced braces and selectors that vanished during a
 * refactor, plus every hook main.js expects to find in the markup.
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const HTML = await readFile(join(ROOT, 'index.html'), 'utf8');
const CSS = await readFile(join(ROOT, 'styles', 'app.css'), 'utf8');

let JSDOM = null;
let VirtualConsole = null;
try {
  ({ JSDOM, VirtualConsole } = await import('jsdom'));
} catch {
  JSDOM = null;
}

const selectorsInJs = [...HTML.matchAll(/id="([^"]+)"/g)].map((m) => m[1]);

test('the markup exposes every id the app wires up', () => {
  const required = [
    'composer', 'prompt', 'promptCount', 'promptMeter', 'promptTips', 'avoid',
    'styleChips', 'styleHint', 'ratioGrid', 'resSeg', 'dimsHint', 'customDims', 'customW', 'customH',
    'modelList', 'modelStatus', 'seed', 'lockSeed', 'diceBtn', 'batchStepper', 'batchValue', 'batchNote',
    'enhance', 'nologo', 'safe', 'private', 'advancedCard', 'refsList', 'addRefBtn', 'pace', 'paceNote',
    'token', 'mockMode', 'generateBtn', 'stopBtn', 'actionsNote', 'statusText', 'statusLabel',
    'cooldown', 'cooldownFill', 'cooldownText', 'shareBtn', 'results', 'emptyState', 'stageBody',
    'library', 'libraryGrid', 'libCount', 'libraryToggle', 'filmstrip', 'historyCount', 'historyClear',
    'historyRedownload', 'helpModal', 'helpBtn', 'themeBtn', 'toasts', 'tierChip', 'tierDot', 'tierText',
    'modelsChip', 'modelsText', 'surpriseBtn', 'clearPromptBtn', 'tryExampleBtn', 'tryMockBtn',
  ];
  const present = new Set(selectorsInJs);
  for (const id of required) assert.ok(present.has(id), `index.html is missing #${id}`);
});

test('no module imports an element id that does not exist', async () => {
  const main = await readFile(join(ROOT, 'js', 'main.js'), 'utf8');
  const used = [...main.matchAll(/\$\('#([a-zA-Z0-9_-]+)'\)/g)].map((m) => m[1]);
  const present = new Set(selectorsInJs);
  const missing = [...new Set(used)].filter((id) => !present.has(id));
  assert.deepEqual(missing, [], `main.js queries ids that are not in the page: ${missing.join(', ')}`);
});

test('the stylesheet parses, and the classes the app adds exist', { skip: JSDOM ? false : 'jsdom not installed' }, () => {
  const errors = [];
  const vc = new VirtualConsole();
  vc.on('jsdomError', (e) => errors.push(String(e.message || e)));
  const dom = new JSDOM(`<!doctype html><html><head><style>${CSS}</style></head><body></body></html>`, { virtualConsole: vc });
  const sheet = dom.window.document.styleSheets[0];
  assert.deepEqual(errors.filter((e) => /css|parse/i.test(e)), [], 'jsdom reported CSS parse errors');
  assert.ok(sheet, 'a stylesheet was parsed');
  const rules = [...sheet.cssRules];
  assert.ok(rules.length > 60, `expected a real stylesheet, got ${rules.length} rules`);

  const text = rules.map((r) => r.cssText).join('\n');
  // Classes created from JS (not present in the HTML) must still be styled.
  for (const cls of [
    'result', 'result__frame', 'result__meta', 'result__badge', 'result__error', 'result__prompt',
    'result__row', 'badge', 'badge--warn', 'badge--accent', 'spec', 'acts', 'act', 'chip', 'ratio',
    'model', 'model__radio', 'model__name', 'model__flag', 'toast', 'toast__i', 'lib-card', 'film',
    'film__thumb', 'film__cap', 'film__kill', 'ref-row', 'note', 'mock-state', 'row', 'field', 'toggle',
  ]) {
    assert.ok(text.includes(`.${cls}`), `.${cls} is generated by JS but has no style rule`);
  }
});

test('both themes resolve every token the components use', () => {
  const blockOf = (re) => CSS.match(re)?.[1] || '';
  const rootBlock = blockOf(/:root\s*\{([\s\S]*?)\n\}/);
  const darkBlock = blockOf(/html\[data-theme="dark"\]\s*\{([\s\S]*?)\n\}/);
  const lightBlock = blockOf(/html\[data-theme="light"\]\s*\{([\s\S]*?)\n\}/);
  assert.ok(darkBlock && lightBlock, 'both theme blocks must exist');

  const tokensUsed = new Set([...CSS.matchAll(/var\((--[a-z0-9-]+)/g)].map((m) => m[1]));
  const definedFor = (themeBlock) => {
    return new Set([...`${rootBlock}\n${themeBlock}`.matchAll(/(--[a-z0-9-]+)\s*:/g)].map((m) => m[1]));
  };
  const darkVars = definedFor(darkBlock);
  const lightVars = definedFor(lightBlock);
  for (const token of tokensUsed) {
    assert.ok(darkVars.has(token), `${token} is used but never defined (dark theme)`);
    assert.ok(lightVars.has(token), `${token} is used but never defined (light theme)`);
  }
  // Sanity: the checks above are not vacuous.
  assert.ok(tokensUsed.size > 12, `expected many custom properties, saw ${tokensUsed.size}`);
  assert.ok(darkVars.has('--bg') && lightVars.has('--bg'));
});

test('responsive + a11y affordances are present', () => {
  assert.match(CSS, /@media \(max-width: 1080px\)/, 'single-column breakpoint');
  assert.match(CSS, /@media \(max-width: 640px\)/, 'phone breakpoint');
  assert.match(CSS, /@media \(prefers-reduced-motion: reduce\)/, 'reduced motion honoured');
  assert.match(CSS, /:focus-visible/, 'keyboard focus ring');
  assert.match(HTML, /class="skip-link"/, 'skip link present');
  assert.match(HTML, /aria-live="polite"/, 'live region for status');
  assert.match(HTML, /<noscript>/, 'noscript explanation');
  // Every icon-only control needs a label.
  for (const id of ['themeBtn', 'helpBtn']) {
    const tag = HTML.match(new RegExp(`<button[^>]*id="${id}"[^>]*>`))?.[0] || '';
    assert.ok(/aria-label|title/.test(tag), `#${id} needs an accessible label`);
  }
});
