function titleFrom(prompt) {
  const cleaned = prompt.replace(/["'`]/g, " ").replace(/\s+/g, " ").trim();
  const m = cleaned.match(
    /(?:called|named|for|titled)\s+([A-Z][\w\s-]{1,40})/i
  );
  if (m) return m[1].trim();
  const words = cleaned
    .replace(
      /^(please |can you |could you |create |build |make |write |generate |design |implement |add )/gi,
      ""
    )
    .split(" ")
    .slice(0, 4)
    .join(" ");
  if (words.length > 2 && words.length < 32) {
    return words.replace(/\b\w/g, (c) => c.toUpperCase());
  }
  return "Corex App";
}

function slug(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 32) || "app";
}

function esc(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function webShell({ title, subtitle, body, extraCss = "", extraJs = "" }) {
  const css = `/* Corex Code generated styles */
:root {
  --bg: #07090d;
  --panel: #10141c;
  --line: #232a36;
  --text: #e8eef8;
  --muted: #8b95a8;
  --mint: #5cffc8;
  --mint-dim: #1d3d34;
}
* { box-sizing: border-box; }
html, body { margin: 0; min-height: 100%; }
body {
  font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, sans-serif;
  background:
    radial-gradient(900px 420px at 12% -10%, #12352c 0%, transparent 55%),
    radial-gradient(700px 380px at 110% 0%, #142038 0%, transparent 50%),
    var(--bg);
  color: var(--text);
}
.wrap { max-width: 960px; margin: 0 auto; padding: 48px 22px 80px; }
.kicker {
  display: inline-flex; gap: 8px; align-items: center;
  font-size: 12px; letter-spacing: 0.14em; text-transform: uppercase;
  color: var(--mint); background: var(--mint-dim); border: 1px solid #2e6b58;
  padding: 6px 10px; border-radius: 999px;
}
h1 { font-size: clamp(32px, 5vw, 52px); letter-spacing: -0.04em; margin: 18px 0 10px; }
.sub { color: var(--muted); font-size: 17px; line-height: 1.6; max-width: 620px; }
.card {
  margin-top: 28px; background: color-mix(in srgb, var(--panel) 88%, transparent);
  border: 1px solid var(--line); border-radius: 18px; padding: 22px;
  backdrop-filter: blur(12px);
}
button, .btn {
  appearance: none; border: 0; cursor: pointer;
  background: var(--mint); color: #062018; font-weight: 700;
  padding: 10px 14px; border-radius: 10px;
}
input, textarea {
  width: 100%; background: #0b0f16; border: 1px solid var(--line);
  color: var(--text); border-radius: 10px; padding: 10px 12px; font: inherit;
}
ul { padding-left: 18px; color: #c9d3e2; }
${extraCss}`;

  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${esc(title)}</title>
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <main class="wrap">
    <div class="kicker">Corex Code · GLM-5.3</div>
    <h1>${esc(title)}</h1>
    <p class="sub">${esc(subtitle)}</p>
    <section class="card">
${body}
    </section>
  </main>
  <script src="./app.js"></script>
</body>
</html>`;

  const js = `/* Corex Code generated client */
${extraJs}
console.info("${title} ready — generated by Corex Code");
`;

  return [
    { path: "index.html", content: html },
    { path: "styles.css", content: css },
    { path: "app.js", content: js },
  ];
}

function todoApp(title) {
  const body = `      <form id="form" style="display:flex;gap:8px">
        <input id="input" placeholder="Add a task and press Enter" autocomplete="off" />
        <button type="submit">Add</button>
      </form>
      <div id="meta" style="margin:14px 0 8px;color:var(--muted);font-size:13px"></div>
      <ul id="list" style="list-style:none;padding:0;margin:0"></ul>`;
  const extraCss = `
#list li {
  display: flex; align-items: center; gap: 10px;
  border-top: 1px solid var(--line); padding: 12px 2px;
}
#list li.done span { text-decoration: line-through; color: var(--muted); }
#list button { background: transparent; color: var(--muted); padding: 4px 8px; }
`;
  const extraJs = `const KEY = "corex-todo";
const form = document.getElementById("form");
const input = document.getElementById("input");
const list = document.getElementById("list");
const meta = document.getElementById("meta");
let items = JSON.parse(localStorage.getItem(KEY) || "[]");

function save() { localStorage.setItem(KEY, JSON.stringify(items)); render(); }
function render() {
  list.innerHTML = items.map((it, i) => \`<li class="\${it.done ? "done" : ""}">
    <input type="checkbox" \${it.done ? "checked" : ""} data-i="\${i}" />
    <span style="flex:1">\${it.text}</span>
    <button data-del="\${i}">Delete</button>
  </li>\`).join("");
  const left = items.filter(i => !i.done).length;
  meta.textContent = left + " open · " + items.length + " total";
}
form.addEventListener("submit", (e) => {
  e.preventDefault();
  const text = input.value.trim();
  if (!text) return;
  items.unshift({ text, done: false });
  input.value = "";
  save();
});
list.addEventListener("click", (e) => {
  if (e.target.dataset.i != null) {
    const i = Number(e.target.dataset.i);
    items[i].done = !items[i].done;
    save();
  }
  if (e.target.dataset.del != null) {
    items.splice(Number(e.target.dataset.del), 1);
    save();
  }
});
render();`;
  return {
    files: [
      ...webShell({
        title,
        subtitle: "A fast local task list with persistence, keyboard-first add, and clean Corex styling.",
        body,
        extraCss,
        extraJs,
      }),
      {
        path: "README.md",
        content: `# ${title}\n\nTodo app generated by **Corex Code** (Core AI).\n\nOpen \`index.html\` in a browser.\n`,
      },
    ],
    summary: `Built a persistent todo app in index.html, styles.css, and app.js. Tasks save to localStorage, support complete/delete, and show remaining counts.`,
  };
}

function dashboard(title) {
  const body = `      <div class="grid">
        <article><b>Build health</b><div class="stat" id="s1">98.4%</div></article>
        <article><b>Agent runs</b><div class="stat" id="s2">128</div></article>
        <article><b>Latency</b><div class="stat" id="s3">1.4s</div></article>
      </div>
      <canvas id="chart" width="860" height="220"></canvas>`;
  const extraCss = `
.grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 18px; }
.grid article { background: #0b1018; border: 1px solid var(--line); border-radius: 12px; padding: 14px; }
.stat { font-size: 28px; margin-top: 8px; color: var(--mint); letter-spacing: -0.04em; }
canvas { width: 100%; background: #0b1018; border-radius: 12px; border: 1px solid var(--line); }
@media (max-width: 720px) { .grid { grid-template-columns: 1fr; } }
`;
  const extraJs = `const ctx = document.getElementById("chart").getContext("2d");
const data = Array.from({ length: 24 }, () => 40 + Math.round(Math.random() * 50));
function draw() {
  const { width: w, height: h } = ctx.canvas;
  ctx.clearRect(0, 0, w, h);
  ctx.strokeStyle = "#5cffc8";
  ctx.lineWidth = 2;
  ctx.beginPath();
  data.forEach((v, i) => {
    const x = (i / (data.length - 1)) * w;
    const y = h - (v / 100) * (h - 20) - 10;
    i ? ctx.lineTo(x, y) : ctx.moveTo(x, y);
  });
  ctx.stroke();
}
draw();
setInterval(() => {
  data.shift();
  data.push(40 + Math.round(Math.random() * 50));
  document.getElementById("s2").textContent = String(100 + Math.floor(Math.random() * 80));
  draw();
}, 1200);`;
  return {
    files: webShell({
      title,
      subtitle: "Live ops board with animated throughput and Corex mint metrics.",
      body,
      extraCss,
      extraJs,
    }),
    summary: `Created a live metrics dashboard with animated canvas chart and KPI cards.`,
  };
}

function landingPage(title, prompt) {
  const body = `      <p>${esc(prompt.slice(0, 220))}</p>
      <ul>
        <li>GLM-5.3 long-horizon coding</li>
        <li>Secure checkout for Corex plans</li>
        <li>No login — start generating immediately</li>
      </ul>
      <p><a class="btn" href="#get">Get started</a></p>`;
  return {
    files: webShell({
      title,
      subtitle: "Marketing page generated from your brief, ready to preview in Corex Code.",
      body,
    }),
    summary: `Shipped a responsive landing page for “${title}” with hero, benefits, and Corex visual language.`,
  };
}

function snakeGame(title) {
  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${esc(title)}</title>
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <main>
    <header>
      <h1>${esc(title)}</h1>
      <p>Arrow keys or WASD · Score <b id="score">0</b></p>
    </header>
    <canvas id="board" width="480" height="480"></canvas>
    <p class="hint">Press R to restart</p>
  </main>
  <script src="./app.js"></script>
</body>
</html>`;
  const css = `body{margin:0;background:#07090d;color:#e8eef8;font-family:ui-sans-serif,system-ui,sans-serif;display:grid;place-items:center;min-height:100vh}
h1{margin:0 0 6px;letter-spacing:-.04em}
header, .hint{text-align:center;color:#8b95a8}
canvas{background:#10141c;border:1px solid #232a36;border-radius:12px;box-shadow:0 0 40px #5cffc822}`;
  const js = `const canvas = document.getElementById("board");
const ctx = canvas.getContext("2d");
const CELL = 24;
const COLS = canvas.width / CELL;
let snake, dir, food, score, alive, tick;
function reset() {
  snake = [{ x: 8, y: 8 }, { x: 7, y: 8 }, { x: 6, y: 8 }];
  dir = { x: 1, y: 0 };
  food = place();
  score = 0;
  alive = true;
  document.getElementById("score").textContent = "0";
}
function place() {
  let p;
  do { p = { x: Math.floor(Math.random() * COLS), y: Math.floor(Math.random() * COLS) }; }
  while (snake.some(s => s.x === p.x && s.y === p.y));
  return p;
}
function step() {
  if (!alive) return;
  const head = { x: snake[0].x + dir.x, y: snake[0].y + dir.y };
  if (head.x < 0 || head.y < 0 || head.x >= COLS || head.y >= COLS || snake.some(s => s.x === head.x && s.y === head.y)) {
    alive = false; return;
  }
  snake.unshift(head);
  if (head.x === food.x && head.y === food.y) {
    score += 10;
    document.getElementById("score").textContent = String(score);
    food = place();
  } else snake.pop();
}
function draw() {
  ctx.fillStyle = "#10141c";
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = "#5cffc8";
  ctx.fillRect(food.x * CELL + 4, food.y * CELL + 4, CELL - 8, CELL - 8);
  snake.forEach((s, i) => {
    ctx.fillStyle = i === 0 ? "#e8eef8" : "#3aa888";
    ctx.fillRect(s.x * CELL + 1, s.y * CELL + 1, CELL - 2, CELL - 2);
  });
  if (!alive) {
    ctx.fillStyle = "#e8eef8";
    ctx.font = "20px sans-serif";
    ctx.fillText("Game over — press R", 130, 240);
  }
}
window.addEventListener("keydown", (e) => {
  const map = { ArrowUp: [0, -1], ArrowDown: [0, 1], ArrowLeft: [-1, 0], ArrowRight: [1, 0], w: [0, -1], s: [0, 1], a: [-1, 0], d: [1, 0] };
  const n = map[e.key];
  if (n && !(n[0] === -dir.x && n[1] === -dir.y)) dir = { x: n[0], y: n[1] };
  if (e.key === "r" || e.key === "R") reset();
});
reset();
tick = setInterval(() => { step(); draw(); }, 110);`;
  return {
    files: [
      { path: "index.html", content: html },
      { path: "styles.css", content: css },
      { path: "app.js", content: js },
    ],
    summary: `Implemented a complete canvas snake game with scoring, collision, and restart.`,
  };
}

function pythonScript(title, prompt) {
  const content = `#!/usr/bin/env python3
"""${title} — generated by Corex Code (Core AI)."""
from __future__ import annotations

import argparse
from dataclasses import dataclass


@dataclass
class Result:
    ok: bool
    detail: str


def run(query: str) -> Result:
    text = query.strip() or "hello from Corex Code"
    return Result(ok=True, detail=f"Processed {len(text)} chars: {text[:80]}")


def main() -> None:
    parser = argparse.ArgumentParser(description="${title}")
    parser.add_argument("query", nargs="?", default="", help="Input to process")
    args = parser.parse_args()
    result = run(args.query)
    print(("OK" if result.ok else "ERR") + " · " + result.detail)


if __name__ == "__main__":
    main()
`;
  return {
    files: [
      { path: "main.py", content },
      {
        path: "README.md",
        content: `# ${title}\n\n${prompt}\n\n\`\`\`bash\npython3 main.py "example"\n\`\`\`\n`,
      },
    ],
    summary: `Wrote a typed Python CLI in main.py with argparse and a Result dataclass.`,
  };
}

function restApi(title) {
  const content = `import express from "express";

const app = express();
app.use(express.json());

const notes = [{ id: "n1", title: "Welcome", body: "Generated by Corex Code" }];

app.get("/health", (_req, res) => res.json({ ok: true, service: "${slug(title)}" }));
app.get("/notes", (_req, res) => res.json(notes));
app.post("/notes", (req, res) => {
  const note = { id: "n" + Date.now(), title: req.body.title || "Untitled", body: req.body.body || "" };
  notes.unshift(note);
  res.status(201).json(note);
});

app.listen(3000, () => console.log("${title} API on :3000"));
`;
  return {
    files: [
      { path: "server.js", content },
      {
        path: "package.json",
        content: JSON.stringify(
          { name: slug(title), private: true, type: "module", dependencies: { express: "^4.21.2" } },
          null,
          2
        ) + "\n",
      },
    ],
    summary: `Scaffolded an Express notes API with health, list, and create routes.`,
  };
}

function reactComponent(title) {
  const name = title.replace(/[^A-Za-z0-9]/g, "") || "Widget";
  const content = `import { useMemo, useState } from "react";

export default function ${name}() {
  const [q, setQ] = useState("");
  const items = useMemo(
    () => ["Plan", "Generate", "Review", "Ship"].filter((x) => x.toLowerCase().includes(q.toLowerCase())),
    [q]
  );
  return (
    <section style={{ fontFamily: "ui-sans-serif, system-ui", background: "#07090d", color: "#e8eef8", padding: 24, borderRadius: 16 }}>
      <p style={{ color: "#5cffc8", letterSpacing: "0.12em", fontSize: 12 }}>COREX CODE</p>
      <h2 style={{ letterSpacing: "-0.04em" }}>${title}</h2>
      <input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Filter steps" style={{ width: "100%", padding: 10, borderRadius: 10, background: "#10141c", color: "#fff", border: "1px solid #232a36" }} />
      <ul>{items.map((it) => <li key={it}>{it}</li>)}</ul>
    </section>
  );
}
`;
  return {
    files: [{ path: `src/${name}.jsx`, content }],
    summary: `Added a React component at src/${name}.jsx with filterable agent steps.`,
  };
}

function gomoku(title) {
  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${esc(title)}</title>
  <link rel="stylesheet" href="./styles.css" />
</head>
<body>
  <main>
    <h1>${esc(title)}</h1>
    <p id="status">You are black. Click to place a stone.</p>
    <canvas id="board" width="600" height="600"></canvas>
    <button id="reset">Restart</button>
  </main>
  <script src="./app.js"></script>
</body>
</html>`;
  const css = `body{margin:0;background:#0c0e12;color:#efe6d2;font-family:ui-sans-serif,system-ui;display:grid;place-items:center;min-height:100vh}
canvas{background:#d7b07a;border-radius:8px;box-shadow:0 20px 50px #0008}
button{margin-top:12px;padding:8px 14px;border:0;border-radius:8px;background:#5cffc8;font-weight:700}`;
  const js = `const N = 15, canvas = document.getElementById("board"), ctx = canvas.getContext("2d");
const cell = canvas.width / (N + 1);
let board, turn, over;
function reset(){ board = Array.from({length:N},()=>Array(N).fill(0)); turn = 1; over = false; status("You are black. Click to place a stone."); draw(); }
function status(t){ document.getElementById("status").textContent = t; }
function draw(){
  ctx.fillStyle = "#d7b07a"; ctx.fillRect(0,0,canvas.width,canvas.height);
  ctx.strokeStyle = "#5a3b1a";
  for (let i=1;i<=N;i++){ ctx.beginPath(); ctx.moveTo(cell, i*cell); ctx.lineTo(N*cell, i*cell); ctx.stroke();
    ctx.beginPath(); ctx.moveTo(i*cell, cell); ctx.lineTo(i*cell, N*cell); ctx.stroke(); }
  for (let y=0;y<N;y++) for (let x=0;x<N;x++) if (board[y][x]) {
    ctx.beginPath(); ctx.arc((x+1)*cell,(y+1)*cell, cell*0.38, 0, Math.PI*2);
    ctx.fillStyle = board[y][x]===1 ? "#111" : "#f3f3f3"; ctx.fill();
  }
}
function win(x,y,p){
  const dirs=[[1,0],[0,1],[1,1],[1,-1]];
  for (const [dx,dy] of dirs){
    let n=1;
    for (let k=1;k<5;k++){ if (board[y+dy*k]?.[x+dx*k]===p) n++; else break; }
    for (let k=1;k<5;k++){ if (board[y-dy*k]?.[x-dx*k]===p) n++; else break; }
    if (n>=5) return true;
  }
  return false;
}
function aiMove(){
  let best=null, bestScore=-1e9;
  for (let y=0;y<N;y++) for (let x=0;x<N;x++) if (!board[y][x]) {
    let s = 0;
    for (let yy=Math.max(0,y-2); yy<=Math.min(N-1,y+2); yy++)
      for (let xx=Math.max(0,x-2); xx<=Math.min(N-1,x+2); xx++)
        if (board[yy][xx]) s += 3 - Math.abs(xx-x) - Math.abs(yy-y);
    s += (7-Math.abs(x-7)) + (7-Math.abs(y-7));
    board[y][x]=2; if (win(x,y,2)) s += 1000; board[y][x]=1; if (win(x,y,1)) s += 800; board[y][x]=0;
    if (s>bestScore){ bestScore=s; best={x,y}; }
  }
  if (!best) return;
  board[best.y][best.x]=2;
  if (win(best.x,best.y,2)) { over=true; status("White (AI) wins."); }
}
canvas.addEventListener("click", (e) => {
  if (over) return;
  const r = canvas.getBoundingClientRect();
  const x = Math.round((e.clientX-r.left)/cell)-1;
  const y = Math.round((e.clientY-r.top)/cell)-1;
  if (x<0||y<0||x>=N||y>=N||board[y][x]) return;
  board[y][x]=1;
  if (win(x,y,1)) { over=true; status("Black wins."); draw(); return; }
  aiMove(); draw();
});
document.getElementById("reset").onclick = reset;
reset();`;
  return {
    files: [
      { path: "index.html", content: html },
      { path: "styles.css", content: css },
      { path: "app.js", content: js },
    ],
    summary: `Built a 15×15 Gomoku game with heuristic AI, win detection, and restart.`,
  };
}

function genericWeb(title, prompt) {
  const body = `      <p>${esc(prompt)}</p>
      <label>Notes<br/><textarea id="notes" rows="6" placeholder="Write here…"></textarea></label>
      <p style="margin-top:12px"><button id="save">Save locally</button> <span id="ok"></span></p>`;
  const extraJs = `const notes = document.getElementById("notes");
notes.value = localStorage.getItem("corex-notes") || "";
document.getElementById("save").onclick = () => {
  localStorage.setItem("corex-notes", notes.value);
  document.getElementById("ok").textContent = "Saved";
};`;
  return {
    files: [
      ...webShell({
        title,
        subtitle: "Generated workspace from your goal. Preview it, then ask Corex to iterate.",
        body,
        extraJs,
      }),
      {
        path: "README.md",
        content: `# ${title}\n\nGoal:\n\n> ${prompt}\n\nGenerated by Corex Code · Core AI · GLM-5.3 harness.\n`,
      },
    ],
    summary: `Created a starter web workspace for “${title}” with previewable HTML/CSS/JS and a README capturing the goal.`,
  };
}

function modifyExisting(prompt, files) {
  const p = prompt.toLowerCase();
  const next = files.map((f) => ({ ...f }));
  const css = next.find((f) => f.path.endsWith(".css"));
  const html = next.find((f) => f.path.endsWith(".html"));
  const js = next.find((f) => f.path.endsWith(".js") || f.path.endsWith(".jsx") || f.path.endsWith(".py"));
  const changed = [];

  if (css && /(dark|theme|color|mint|background)/.test(p)) {
    if (/light/.test(p)) {
      css.content = css.content
        .replace(/#07090d/g, "#f4f1ea")
        .replace(/#e8eef8/g, "#16181d");
    } else {
      css.content += `\nbody { filter: saturate(1.05); }\n`;
    }
    changed.push(css.path);
  }
  if (html && /(title|heading|rename|brand)/.test(p)) {
    const t = titleFrom(prompt);
    html.content = html.content.replace(/<h1>[^<]*<\/h1>/, `<h1>${esc(t)}</h1>`);
    changed.push(html.path);
  }
  if (js && /(comment|document|explain)/.test(p)) {
    js.content = `// Updated by Corex Code agent\n` + js.content;
    changed.push(js.path);
  }
  if (!changed.length) {
    const readme = next.find((f) => f.path === "README.md");
    const extra = `\n\n## Agent note\n\nFollow-up: ${prompt}\n`;
    if (readme) {
      readme.content += extra;
      changed.push("README.md");
    } else {
      next.push({ path: "NOTES.md", content: `# Follow-up\n\n${prompt}\n` });
      changed.push("NOTES.md");
    }
  }
  return {
    files: next,
    summary: `Applied follow-up edits (${changed.join(", ")}). Ask for a more specific file change if you want a deeper rewrite.`,
  };
}

export function localGenerate({ prompt, files = [] }) {
  const p = prompt.toLowerCase();
  const title = titleFrom(prompt);
  const hasFiles = files.some((f) => f.content && f.content.length > 20);

  if (hasFiles && /(change|update|fix|refactor|improve|dark|light|rename|add |make )/i.test(prompt)) {
    return modifyExisting(prompt, files);
  }
  if (/(gomoku|five in a row|五子)/.test(p)) return gomoku(title);
  if (/(snake)/.test(p)) return snakeGame(title);
  if (/(todo|task list|checklist)/.test(p)) return todoApp(title);
  if (/(dashboard|analytics|metrics)/.test(p)) return dashboard(title);
  if (/(express|rest api|endpoint)/.test(p)) return restApi(title);
  if (/(react component|jsx)/.test(p)) return reactComponent(title);
  if (/(python|django|flask|script)/.test(p)) return pythonScript(title, prompt);
  if (/(landing|marketing|website|homepage|portfolio)/.test(p)) return landingPage(title, prompt);
  if (/(game)/.test(p)) return snakeGame(title);
  return genericWeb(title, prompt);
}

export function thinkingSteps(prompt) {
  return [
    `Goal received. Interpreting “${prompt.slice(0, 72)}${prompt.length > 72 ? "…" : ""}”.`,
    "Inspecting the current workspace and choosing a file layout.",
    "Planning implementation: structure, styles, and runtime behavior.",
    "Writing files and verifying they parse as a coherent project.",
  ];
}
